### ISSUE TITLE
How to embed Custom Content inside ngx-tile??

### ISSUE THREAD

**Issue by adonis1116** [sheikalthaf/ngx-carousel#14]
I wanted to use Fixed-Width tile and embed my custom contents for ngx-tile. But the `'white-space'` property  of  .ngxcarousel-items makes the expected result wrong..
```
<ngx-carousel 
    [inputs]="carouselTile" 
    (carouselLoad)="carouselTileLoad($event)">
    <ngx-tile NgxCarouselItem *ngFor="let Tile of purchasedProducts">
        <ngx-product-simple [image]="image">
        </ngx-product-simple>
    </ngx-tile>
</ngx-carousel>
```
Could you provide me your code about Fixed-Width sample ?
or I would like you provide the complete usage of it..

**Comment by sheikalthaf** [comment]
If you want your `ngx-tile` to be fixed in width simply pass data in grid like this `grid: {xs: 0, sm: 0, md: 0, lg: 0, all: 200}`. In grid `all` denote that it is a fixed width

**Comment by sheikalthaf** [comment]
Any screenshot about the result? Make sure you don't fix the width inside ngx-tile. Carousel will fixed the width by above comment

**Comment by adonis1116** [comment]
This is not the result what I expected. I tested your Tile sample ( not fixed-width ) and it works well..
But when I embed my `ngx-product-simple` to your `ngx-tile`, then it shows the result below..

![2017-10-09 at 13-17-41](https://user-images.githubusercontent.com/16154269/31325848-44eb80c4-acf4-11e7-8045-c5f3a2adf1f6.png)

How to fix this problem? I want you to provide me your Demo code if you can.

**Comment by adonis1116** [comment]
Or how can I use Image tag instead of Div with Background in your sample?
Thanks

**Comment by adonis1116** [comment]
I solved my issue. Thanks for your effort.
Very useful Carousel Module. Cheers!!

**Comment by sheikalthaf** [comment]
can i have info about how u solved your problem. it will help me to make changes in carousel

**Comment by adonis1116** [comment]
I used the HTML sample code from your sample. I have changed nothing. Only styling.
BTW, could you provide the mode for change the position of buttons like this??

![2017-10-13 at 18-39-06](https://user-images.githubusercontent.com/16154269/31542727-d22bdbc4-b045-11e7-95d2-05677fed2e1d.png)

I was trying to do it by embedding the two arrow buttons into one div and style the parent div. But the buttons were hidden when they were embedded.

**Comment by sheikalthaf** [comment]
```css
.leftRs {
    position: absolute;
    top: -50px;
    bottom: 0;
    width: 50px;
    height: 50px;
    box-shadow: 1px 2px 10px -1px rgba(0,0,0,.3);
    border-radius: 999px;
    right: 65px;
}
.rightRs {
    position: absolute;
    top: -50px;
    bottom: 0;
    width: 50px;
    height: 50px;
    box-shadow: 1px 2px 10px -1px rgba(0,0,0,.3);
    border-radius: 999px;
    right: 0;
}
```

you can apply custom css to your buttons. try the above css
