### ISSUE TITLE
How to remove shadow in a tile

### ISSUE THREAD

**Issue by NicCyclePath** [sheikalthaf/ngx-carousel#35]
This may seem like a dumb question. But I have desperately seeking for the answer. 
I have tried to use "box-shadow: none !important;" but It wasn't working.

PLZ MERCY ME *-*

**Comment by sheikalthaf** [comment]
```css
ngx-tile /deep/ .tile {
    box-shadow: none;
}
```

try this
